function EvidencePage({ logs = [], auditData, onLogSelect }) {
  return (
    <section className="evidence-page">
      <div className="hero-row compact">
        <div>
          <p className="eyebrow">Evidence / Audit</p>
          <h1>Splunk Evidence Trail</h1>
          <p>
            Raw supply chain telemetry and response actions generated by the
            containment layer.
          </p>
        </div>
      </div>

      <div className="evidence-grid">
        <section className="evidence-panel">
          <div className="panel-heading">
            <div>
              <p className="eyebrow">Splunk Events</p>
              <h2>{logs.length} events</h2>
            </div>
          </div>

          <div className="table-shell">
            <table>
              <thead>
                <tr>
                  <th>Time</th>
                  <th>Stage</th>
                  <th>Pod</th>
                  <th>Package</th>
                  <th>Status</th>
                  <th>Severity</th>
                </tr>
              </thead>

              <tbody>
                {logs.map((log, index) => (
                  <tr key={`${log.timestamp}-${index}`} onClick={() => onLogSelect(log)}>
                    <td>{log.timestamp}</td>
                    <td>{log.event_type}</td>
                    <td>{log.pod}</td>
                    <td>{log.package}</td>
                    <td>{log.status}</td>
                    <td>{log.severity}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        <section className="audit-panel">
          <div className="panel-heading">
            <div>
              <p className="eyebrow">Response Audit</p>
              <h2>{auditData?.count || 0} actions</h2>
            </div>
          </div>

          <div className="audit-list">
            {(auditData?.events || []).map((event) => (
              <article key={event.id}>
                <span>{event.status}</span>
                <strong>{event.action_type}</strong>
                <p>{event.target}</p>
              </article>
            ))}
          </div>
        </section>
      </div>
    </section>
  );
}

export default EvidencePage;